config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  get '/tutor', to: 'static_pages#new_tutor'
  get '/student', to: 'static_pages#new_student'

  get '/login', to: 'sessions#new'
  # a create and destroy route on your sessions
  resources :sessions, only: [:create, :destroy]

  get 'events/search', to: 'events#search'
  resources :events, except: [:destroy] do
    resources :comments
  end
  resources :users
  resources :needs
  resources :groups
  resources :locations

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  description :text
#  user_id     :integer
#  event_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/comments_controller.rb
class commentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.event_id = Event.find(params[:event_id])
    if @comment.save
      flash[:success] = ['Comment successfully created']
      redirect_to comment_url(@comment)
    else
      flash.now[:errors] = @comment.errors
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    flash[:notice] = 'Comment Updated'
    redirect_to comments_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment Removed'
    redirect_to comments_path
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def index
    @comments = Comment.all
    render :index
  end

  private
  def comment_params
    params.require(:comment).permit(:description)
  end

end

app/views/comments/edit.html.erb
<h2>Add New Comment</h2>
<%= form_for @comment do |f| %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", comments_path, class:"btn btn-default" %>

<% end %>

app/views/comments/index.html.erb
<h1>ALL THE EVENTS ARE HERE MUHHHHH</h1>

<br>
<%= link_to "New Event", new_event_path, class:"btn btn-primary"  %>
<br>

<% @events.each do |event| %>
  <h2><%= link_to event.name, event_path(event)%></h2>
  <%= link_to 'Edit', edit_event_path(event.id), class:"btn btn-primary"  %> | <%= link_to 'Delete', event_path(event.id), class:"btn btn-primary", method: :delete, data: {confirm: 'Are you sure?'} %><br>
<% end %>

app/views/comments/new.html.erb
<h2>Add New Event</h2>
<%= form_for @event do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </div>

  <div class="form-group">
    <%= f.label :attendees %>
    <%= f.text_field :attendees %><br>
  </div>

  <div class="form-group">
    <%= f.label :time_start %>
    <%= f.text_field :time_start %><br>
  </div>

  <div class="form-group">
    <%= f.label :time_end %>
    <%= f.text_field :time_end %><br>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.select :subject_id, Subject.all.collect {|x| [x.name, x.id]} %><br>
  </div>

  <div class="form-group">
    <%= f.label :user %>
    <%= f.select :user_id, User.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]} %><br>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.select :location_id, Location.all.collect {|x| [x.street + ' ' + x.suite, x.id]} %><br>
  </div>

  <div class="form-group">
    <%= f.label :group %>
    <%= f.select :group_id, Group.all.collect {|x| [x.name, x.id]} %><br>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", events_path, class:"btn btn-default" %>

<% end %>

app/views/comments/search.html.erb
<h1>Tutoring Sessions</h1>
<%= render @events %>

app/views/comments/show.html.erb
<h2><%= @event.name %></h2>

<h5><%= @event.attendees %></h5><br>
<h5><%= @event.time_start %></h5><br>
<h5><%= @event.time_end %></h5><br>
<h5><%= @event.description %></h5><br>
<h5><%= @event.subject.name %></h5><br>
<h5><%= @event.user.first_name %> <%= @event.user.last_name %></h5><br>
<h5><%= @event.location.street %></h5><br>
<h5><%= @event.group.name %></h5><br>



<%= link_to 'Edit', edit_event_path(@event.id) %> | <%= link_to 'Delete', event_path(@event.id), method: :delete, data: {confirm: 'Are you sure?'} %>