config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  get '/tutor', to: 'static_pages#new_tutor'
  get '/student', to: 'static_pages#new_student'

  get '/login', to: 'sessions#new'
  # a create and destroy route on your sessions
  resources :sessions, only: [:create, :destroy]

  get 'events/search', to: 'events#search'
  resources :events, except: [:destroy] do
    resources :comments
  end
  resources :users
  resources :needs
  resources :groups
  resources :locations

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Group < ActiveRecord::Base

  # has_and_belongs_to_many :users, join_table: 'members'
  has_many :members
  has_many :users, through: :members
  has_many :events
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      current_user.groups << @group
      flash[:success] = ["New group successfully created"]
      redirect_to "/groups/#{@group.id}"
    else
      flash[:errors] = @group.errors
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    flash[:notice] = 'Group Updated'
    redirect_to groups_path
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'group Removed'
    redirect_to groups_path
  end

  def index
    @groups = Group.all
  end

  private
  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/views/groups/index.html.erb
<% @page_title = 'Tutoring Session Volunteers' %>
<%= render partial: 'layouts/header', locals: {page_title: @page_title} %>

<%= link_to "New Group", new_group_path, class:"btn btn-primary"  %><br>

<% @groups.each do |group| %>
  <h2><%= link_to group.name, group_path(group)%></h2>
  <h5><%= group.description %></h5>
  <%= link_to 'Edit', edit_group_path(group.id), class:"btn btn-primary"  %> | <%= link_to 'Delete', group_path(group.id), class:"btn btn-primary", method: :delete, data: {confirm: 'Are you sure?'} %><br>
<% end %>

app/views/groups/new.html.erb
<% @page_title = 'Create a Tutoring Group' %>
<%= render partial: 'layouts/header', locals: {page_title: @page_title} %>

<%= form_for @group do |f| %>
  <h4 class='gray'>Your tutoring group's name</h4>
  <div>
    <%= f.text_field :name, placeholder: 'e.g. San Francisco Math SAT Group', class:"form-control" %><br>
  </div>

  <h4 class='gray'>What is this tutoring group about?</h4>
  <div>
    <%= f.text_field :description, placeholder: 'This tutorial group is for...', class:"form-control" %><br>
  </div>

  <%= f.submit "Confirm", class:'btn form-control confirm' %><br>

<% end %>

app/views/groups/show.html.erb
<% @page_title = 'Tutoring Group Info' %>
<%= render partial: 'layouts/header', locals: {page_title: @page_title} %>
<div>
<h2><%= @group.name %></h2>
<strong>Tutors<strong>
<% @group.users.where(role: 1).each do |tutor| %>
  <img class="avatar" src="http://edushyster.com/wp-content/uploads/2012/10/swf.jpg" />
<% end %>
<h5><%= @group.description %></h5>


<div class="row" style="border: solid 1px gray;">
  <br>
  <div class="awwpx left clearfix" style="float: left;">
    <span class="glyphicon glyphicon-calendar"><%= link_to 'Create Session', new_event_path %></span>
  </div>

  <div class="awwpx right clearfix" style="float: right;">
    <span class="glyphicon glyphicon-cog"> <%= link_to 'Change Settings', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' %></span>
  </div>
</div>
<br>
<%= link_to "Add Event", new_event_path,class:'btn form-control confirm' %><br>
<!-- <%= link_to "Join This Group", '/',class:'btn form-control confirm' %><br> -->

<br>

<% @group.events.each do |event| %>
  <%= event.time_start %><%= event.name %> <%= link_to '', join_event_path, class:'glyphicon glyphicon-plus-sign' %>
<% end %>