config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  get '/tutor', to: 'static_pages#new_tutor'
  get '/student', to: 'static_pages#new_student'

  get '/login', to: 'sessions#new'
  # a create and destroy route on your sessions
  resources :sessions, only: [:create, :destroy]

  get 'events/search', to: 'events#search'
  resources :events, except: [:destroy] do
    resources :comments
  end
  resources :users
  resources :needs
  resources :groups
  resources :locations

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  first_name    :string
#  last_name     :string
#  username      :string
#  role          :integer
#  grade         :string
#  school        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class User < ActiveRecord::Base

  validates :username, presence: true, uniqueness: true
  validates :password, presence: { message: "Password can't be blank" }

  has_many :members
  has_many :groups, through: :members
  has_and_belongs_to_many :subjects, join_table: 'studies'

  has_many :happenings
  has_many :events, through: :happenings, source: :event
  has_many :created_events, class: "Event", foreign_key: :user_id

  has_many :comments
  has_many :needs

# how you log a registered user in

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def index
  @user = User.all
  render :index
end

def create
  @user = User.new(user_params)
  @user.save
  login(@user)
  flash[:notice] = 'User Added'
  redirect_to events_path
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  @user.update(user_params)
  flash[:notice] = 'User Updated'
  redirect_to users_path
end

def destroy
  @user = User.find(params[:id])
  @user.destroy
  flash[:notice] = 'User Removed'
  redirect_to users_path
end

def index # list of all
  @users = User.all
end

def show # individual
  @user = User.find(params[:id])
end

private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :role, :grade, :school, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.first_name %>
<%= user.last_name %>
<%= user.username %>
<% end %>

<%= link_to "New Event", new_event_path, class:"btn btn-primary"  %>
<%= link_to "New Location", new_location_path, class:"btn btn-primary"  %>
<%= link_to "New Group", new_group_path, class:"btn btn-primary"  %>

app/views/users/new.html.erb
<% @page_title = 'After-school Tutoring Sign Up' %>
<%= render partial: 'layouts/header', locals: {page_title: @page_title} %><br>
<div id="wrapper">

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
        <div class="alert-error"><%= msg %></div>
      <% end %>
    <% end %>

  <div class="form-group">
    <%= f.label :role %>
    <%= f.select :role, ['I need tutoring', 'I want to be a tutor']%>
  </div>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class:'form-control', placeholder: 'John' %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class:'form-control', placeholder: 'Smith' %>
  </div>

  <div class="form-group">
    <%= f.label :school %>
    <%= f.text_field :school, class:'form-control', placeholder: 'Your-town Area School District, College, or University' %>
  </div>

  <div class="form-group">
    <%= f.label :grade %>
    <%= f.select :grade, ['1rst Grade', '2nd Grade', '3rd Grade', '4rth Grade', '5th Grade', '6th Grade', '7th Grade', '8th Grade', '9th Grade Freshman', '10th Grade Sophmore', '11th Grade Junior', '12th Grade Senior','College Freshman', 'College Sophmore', ' College Junior', 'College Senior' , 'Other']%>
  </div>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: 'Becky' %><br>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: 'Becky@badatstarcraft.org' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, placeholder: 'Password' %>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>

  <%= link_to "Cancel", users_path %>
  <% end %>

app/views/users/registration.html.erb
<h2>After-school Tutoring Sign Up</h2>
<div id="wrapper">

<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |msg| %>

<div class="alert-error"><%= msg %></div>
<% end %>
<% end %>

<div>
  <%= f.label :role %>
<%= f.select :role, ['I need tutoring', 'I want to be a tutor']%>
</div>

<div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class:'form-control', placeholder: 'John' %><br>
</div>

<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class:'form-control', placeholder: 'Smith' %><br>
</div>

<div>
  <%= f.label :school %>
  <%= f.text_field :school, class:'form-control', placeholder: 'Your-town Area School District, College, or University' %><br>
</div>

<div>
  <%= f.label :grade %>
<%= f.select :grade, ['1rst Grade', '2nd Grade', '3rd Grade', '4rth Grade', '5th Grade', '6th Grade', '7th Grade', '8th Grade', '9th Grade Freshman', '10th Grade Sophmore', '11th Grade Junior', '12th Grade Senior','College Freshman', 'College Sophmore', ' College Junior', 'College Senior' , 'Other']%>
</div>

<div>
  <%= f.label :email %>
  <%= f.text_field :username, placeholder: 'mymail@mail.com' %><br>
</div>

<div>
  <%= f.label :password %>
  <%= f.text_field :password_hash, placeholder: 'X8df!90EO' %><br>
</div>

<div>
  <%= f.label :password %>
  <%= f.text_field :passwordsignup_confirm, placeholder: 'X8df!90EO' %><br>
</div>

<%= f.submit "Submit" %>

<%= link_to "Cancel", users_path %>
<% end %>

app/views/users/show.html.erb
<h2>Show the User Profile</h2>
<%= @user.first_name %>
<%= @user.last_name %>

app/views/users/signin.html.erb
<h2>After-school Tutoring Sign In</h2>
<div id="wrapper">

<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |msg| %>

<div class="alert-error"><%= msg %></div>
<% end %>
<% end %>

<div>
  <%= f.label :email %>
  <%= f.text_field :username, placeholder: 'mymail@mail.com' %><br>
</div>

<div>
  <%= f.label :password %>
  <%= f.text_field :password, placeholder: 'X8df!90EO' %><br>
</div>

<%= f.submit "Submit" %>

<%= link_to "Cancel", users_path %>
<% end %>