config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  get '/tutor', to: 'static_pages#new_tutor'
  get '/student', to: 'static_pages#new_student'

  get '/login', to: 'sessions#new'
  # a create and destroy route on your sessions
  resources :sessions, only: [:create, :destroy]

  get 'events/search', to: 'events#search'
  resources :events, except: [:destroy] do
    resources :comments
  end
  resources :users
  resources :needs
  resources :groups
  resources :locations

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  street     :string
#  suite      :string
#  city       :string
#  state      :string
#  zip        :string
#  name       :string
#  phone      :string
#  contact    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
  has_many :needs
  has_many :users # how does this work?
  has_many :events
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = ["New location successfully created"]
      redirect_to locations_path
    else
      flash[:errors] = @location.errors
      render :new
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    @location.update(location_params)
    flash[:notice] = 'Location Updated'
    redirect_to locations_path
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    flash[:notice] = 'Location Removed'
    redirect_to locations_path
  end

  def index
    @locations = Location.all
  end

  private
  def location_params
    params.require(:location).permit(:street, :suite, :city, :state, :zip, :name, :phone, :contact)
  end
end

app/views/locations/_new_location.html.erb
<div class = 'tutoringvenue'>

  <form name="venue" action="/locations/create" method="post">
    <label for="zipcode">Zip code:</label>
    <input type="text" name="zipcode" id="zipcode" />

    <label for="name">Venue name:</label>
    <input type="text" name="name" id="name" />

    <label for="address">Address:</label>
    <input type="text" name="address" id="address" />

    <label for="contact">Primary contact name:</label>
    <input type="text" name="contact" id="contact" />

    <label for="phone">Telephone:</label>
    <input type="text" name="phone" id="phone" />

    <input type="submit" value="Add venue">
  </form>

</div>

app/views/locations/edit.html.erb
<h2>Edit Location</h2>
<%= form_for @location do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </div>

  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street %><br>
  </div>

  <div class="form-group">
    <%= f.label :suite %>
    <%= f.text_field :suite %><br>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city %><br>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state %><br>
  </div>

  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip %><br>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone %><br>
  </div>

  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :contact %><br>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", locations_path, class:"btn btn-default" %>

<% end %>

app/views/locations/index.html.erb
<h1>ALL THE LOCATIONS ARE HERE MUHHHHH</h1>

<br>
<%= link_to "New Location", new_location_path, class:"btn btn-primary"  %>
<br>

<% @locations.each do |location| %>
  <h2><%= link_to location.name, location_path(location)%></h2>
  <%= link_to 'Edit', edit_location_path(location.id), class:"btn btn-primary"  %> | <%= link_to 'Delete', location_path(location.id), class:"btn btn-primary", method: :delete, data: {confirm: 'Are you sure?'} %><br>
<% end %>

app/views/locations/new.html.erb
<h2>Add New Location</h2>
<%= form_for @location do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </div>

  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street %><br>
  </div>

  <div class="form-group">
    <%= f.label :suite %>
    <%= f.text_field :suite %><br>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city %><br>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state %><br>
  </div>

  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip %><br>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone %><br>
  </div>

  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :contact %><br>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", locations_path, class:"btn btn-default" %>

<% end %>

app/views/locations/show.html.erb
<h2><%= @location.name %></h2>

<h5><%= @location.street %></h5><br>
<h5><%= @location.suite %></h5><br>
<h5><%= @location.city %></h5><br>
<h5><%= @location.state %></h5><br>
<h5><%= @location.zip %></h5><br>
<h5><%= @location.name %></h5><br>
<h5><%= @location.contact %></h5><br>
<h5><%= @location.phone %></h5><br>

<%= link_to 'Edit', edit_location_path(@location.id) %> | <%= link_to 'Delete', location_path(@location.id), method: :delete, data: {confirm: 'Are you sure?'} %>